jonhoo/flurry

src/lib.rs
tests/basic.rs

My expectation is that a regular user of the map should not be required to use `unsafe`. `Shared` requires that you use unsafe to dereference to the value. Instead, tie the reference to the lifetime of the guard passed into the get method

Remove the use of Shared from the public API to avoid consumers being required to use unsafe to use the map

---

azure-pipelines.yml
deny.toml

Check that we don't depend on vulnerable crate versions, have duplicates in our dependency graph, or depend on licenses that it's not okay for us to depend on.

Add cargo deny checks

---

src/iter/iter.rs
src/iter/mod.rs
src/lib.rs
tests/jdk/map_check.rs

I was following part of you stream earlier today and decided to try my hand at porting some of the other Java tests from [MapCheck.java](https://hg.openjdk.java.net/jdk/jdk/file/345266000aba/test/jdk/java/util/concurrent/ConcurrentHashMap/MapCheck.java).
The contains_key tests were pretty straightforward since you already implemented `contains_key`. Those are `t4` and `t7`.
During the stream, you mentioned that `NodeIter` is a private Iterator which could be the basis for public iterators on keys, values, and entries. I've done that in a new file `src/iter/iter.rs` with three new structs `Iter`, `Keys`, and `Values` (similar to `std::collections::HashMap`). I added some of my own tests for the new `iter()`, `keys()`, and `values()` methods and ported `ittest1`, `ittest2`, and `ittest3` …

Add iter, keys, and values with Java tests

---

src/lib.rs
tests/basic.rs

This pr implements the `PartialEq`, `Eq` and the `Debug` traits.
These additions were requested in #10

Implement Eq and Debug traits

---

src/lib.rs
src/node.rs
tests/borrow.rs

This matches the standard library's approach to key lookups, allowing
any `Q where K: Borrow<Q>`. This lets you use unowned values to query
the maps, e.g. a map with `K = String` can be accessed with `Q = str`.

Allow borrowed keys for lookups

---

src/lib.rs
src/node.rs
tests/basic.rs

It turns out that `find` would always return the first entry in a bucket, as longs as the desired entry was found somewhere in the bucket. This can be replicated by reverting the change in `lib/node.rs`.
At the same time, I added two new constructors of `FlurryHashMap`, which can take a custom **Hasher**: the architecture allowed other hashers to be used, but we couldn't actually build any `Flurry` instances beforehand.

Fixed bug in `Node#find`

---

Cargo.toml

It's only used in a few tests, not in the crate proper.

Move rand to [dev-dependencies]

---

src/map.rs
src/node.rs

This tackles #9 and moves the argument to the definition of BinEntry::Moved, so as to reduce redundancy.

Finish safety argument for BinEntry::Moved

---

src/node.rs

Just wanted to normalize the two branches of the `match` statement.

Replace `break` with `return`, where the loop immediately returns anyway

---

src/iter/iter.rs
src/lib.rs
src/map.rs

Currently, docs.rs is broken for flurry: https://docs.rs/crate/flurry/0.0.2/builds/215675. This PR fixes it.
I think it would probably be a good idea to fail the build if doclinks are broken. However, I'm not familiar with azure-pipelines, so I'm not entirely sure how to set this up.

Fix broken doclinks which are causing the docs to fail to build.

---

src/map.rs
tests/basic.rs

Implemented `retain` for HashMap
Implemented `retain` tests for empty map, retain all elements, retain none elements and retain arbitrary elements

retain method

---

Cargo.toml
azure-pipelines.yml
src/map.rs

Currently blocked on https://github.com/rust-lang/miri/pull/1150 landing on nightly and on https://github.com/crossbeam-rs/crossbeam/pull/458.

Add miri CI test

---

src/map.rs
tests/basic.rs

This pull request contains the compute_if_present method, which is the simplest one among the reservation-based methods mentioned in #12 since it does not require ReservationNodes.
I took most of the code from put and remove.
For now, I only added basic tests but I also want to port some of the Java tests.

Implement compute_if_present

---

Cargo.toml
src/lib.rs
src/map.rs
tests/basic.rs
tests/jdk/map_check.rs
tests/jsr166.rs

This steals a bunch of the commits from #44 that are _not_ related to `no_std`, and should land independently of whether we merge `no_std` support.

Steal good commits from #44

---

src/node.rs
tests/basic.rs

I noticed that one of the areas of the code which had low test coverage was the [BinEntry::Moved branch in node.rs](https://github.com/jonhoo/flurry/blob/master/src/node.rs#L107). This test is designed to exercise that codepath. At least on my machine it seems to exercise the codepath but it is non-deterministic whether it will actually encounter the path.

Add test which attempts to encounter a concurrent resize and retrieval

---

benches/flurry_hashbrown.rs

The benchmarks adapted from `hashbrown` introduced by #43 were missing the `clear()` method on the map and thus currently construct a new map every iteration. Now that we have `clear()` thanks to #42, we should fix this and make the benchmarks identical.

Use `clear()` in benchmarks

---

src/iter/traverser.rs
src/map.rs
src/node.rs
src/raw/mod.rs

This originates from #50 and tries to achieve performance improvements by instantiating only one `BinEntry::Moved` per table, as for all moved bins inside a table the `Moved` points to the same next table. In particular, this tries to reduce the amount of allocations of `Moved` by `Owned::new`, only `load`ing more shared pointers to the `Moved` instead.
This is submitted as a draft for the following reasons:
- ~~the history for this contains the changes in #55, which is still pending approval~~ (Edit: changed that)
- the previous implementation of `Table::drop` [contains a section](https://github.com/jonhoo/flurry/blob/b6b360feffa3ae6515739f6bf341fa27a7d0dc87/src/raw/mod.rs#L86-L98) which iterates through all bins, drops `Moved` entries and checks that none of the bins are non-empty. With …

Share BinEntry::Moved across all moved bins in a table

---

azure-pipelines.yml
src/map.rs

This works around rust-lang/rust#53945 using the trick proposed in https://github.com/rust-lang/rust/issues/53945#issuecomment-426824324.

Fix santitizer for doctests

---

CHANGELOG.md
Cargo.toml
azure-pipelines.yml

This removes the patch that incorporates crossbeam-rs/crossbeam#458,
since that PR also bumps the version number, and 0.9 doesn't exist on
crates.io. This in turn means that the miri test has to be disabled for
this release in particular. I'll push a commit after release that
restores it and the crossbeam patch.
This commit also adds a changelog!

Prep for release of 0.1.0

---

src/map.rs

Follow-on work from #64
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/flurry/66)

Remove Clone for with_capacity with simple presize

---

src/map.rs
src/map_ref.rs
tests/basic.rs

Also removes `get_and`, because it's pretty useless now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/flurry/67)

Fix up inline annotations.

---

src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/flurry/71)

fix two typos in crate documentation

---

azure-pipelines.yml

@RalfJung [suggested](https://github.com/jonhoo/flurry/commit/7bd22c62eac86a8e0d3426b5a4c790e9850e5843#r37880279) we use `cargo miri setup`, so we do. I've also pinned the nightly to one that has miri since the current nightly does not (https://github.com/rust-lang/rust/issues/70055).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/flurry/73)

Proper miri setup + pin miri nightly

---

src/map.rs

This also fixes a memory leak when `no_replacement = true` (which no
code was doing yet luckily). Previously, if an insert failed due to
`no_replacement`, the provided `value` would be leaked. Now, it is
instead recovered and provided with the `Exists` return value from
`put`.
Also needed for #74.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/flurry/77)

Allow recovering value on failed insert

---

src/node.rs

It is possible for someone to try to wake a waiting thread while that
thread is spinning. In that case, the waiting thread may decide to free
its waker just before the waking thread tries to wake the waiting one,
resulting in a use-after-free.
This fixes that by deferring the freeing of the waker until the next
epoch.
Seems to fix #84.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/flurry/85)

Do not free waker until safe

---

src/map.rs

Changes the map's element count to be stored as a signed integer, to avoid panics if the count is updated by for example two removing and one inserting thread out of order.
In order to not report a negative size to users, `len` is adjusted to return `0` if the actual count is negative. This is translated from [the Java implementation](https://github.com/jonhoo/flurry/blob/master/jsr166/src/ConcurrentHashMap.java#L880), but without the upper bounds check, since for us the storage data type (`isize`) cannot be larger than the maximal value of the return type (`usize`).
Note that this means that technically the same race condition still exists at the upper bound, however the map's `MAXIMUM_CAPACITY` is way below `isize::MAX`.
Closes #86.
---
This change is [<img …

store element count as isize and clamp len to >= 0

---

src/map.rs

Removes the erroneous assumption that attempts to treeify a bin should always be successful and find a regular (linear) bin when loading the bin from the table.
Instead, it is also possible to find a `Moved` entry if the bin was moved in the meantime, or a `Tree` if another thread already treeified the bin before the first thread got to that point.
Loading a `TreeNode` remains an error, since these shouldn't be the head of a bin.
Closes #83. Refer to this issue or the comment introduced for the above cases with this commit for further explanation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/flurry/87)

no longer panic upon seeing a moved or treeified bin in treeify_bin

---

src/lib.rs
src/map.rs
tests/regressions.rs

Early return with an indication that the requested key already existed and a reference back to the value trying to be inserted.
Fixes #90. 
I also took the liberty to add a new `issues.rs` test file to contain reproducible bugs that should now be fixed, so we will know should they appear again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/flurry/91)

Early return in the slow path of `put` if key already exists and `no_replacement` is true

---

benches/flurry_dashmap.rs
benches/flurry_hashbrown.rs

Benchmarks are still using `epoch` which was recently removed since `seize` was adopted for garbage collection. I needed to fix this in order for me to make some benchmarks for the concurrent counter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/flurry/106)

Benchmark fix

---

README.md
src/lib.rs

Updates outdated references to source files.
Previously the link in `src/lib.rs` didn't include the revision, while `README.md` did. Was this intentional? 7fc19d97538434499ce93aba9e695eada69fd89c updates only the revision
It may be better to update the links to [an archive.org snapshot](https://web.archive.org/web/20221004094436/https://gee.cs.oswego.edu/cgi-bin/viewcvs.cgi/jsr166/jsr166/src/main/java/util/concurrent/ConcurrentHashMap.java?revision=1.323&view=markup) instead
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/flurry/110)

Fix references to Java source files

---

.github/workflows/safety.yml
Cargo.lock
Cargo.toml
src/iter/mod.rs
src/map.rs
src/node.rs
src/raw/mod.rs
src/reclaim.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/flurry/123)

Update `seize` to 0.3

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/map.rs
src/set.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/flurry/124)

Release 0.5.1

---

src/map.rs

Just noticed this when I was reading the `retain` docs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/flurry/125)

chore: fix typo in `retain_force` method doc

---

.github/workflows/check.yml
deny.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/flurry/126)

Make CI happy again

---

src/iter/traverser.rs
src/map.rs
src/node.rs
src/raw/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jonhoo/flurry/130)

some stylistic improvements
